# Match up everyone

In [1]:
# imports
from importlib import reload
#import earthaccess

import os
import numpy as np

import pandas
from matplotlib import pyplot as plt
from shapely.geometry import Polygon, Point

from ocpy.utils import io as ocpy_io

from remote_sensing.plotting import globe
from remote_sensing.download import earthaccess as rs_ea

import grab_pace_granules

# Load up BGC

In [2]:
df = pandas.read_csv('argo_bgc_profiles_bbp.csv')

## Cut on date

In [3]:
time = pandas.to_datetime(df.time.values)
old_enough = time > pandas.Timestamp('2024-04-01')

In [4]:
argo_pace = df[old_enough]
pace_times = pandas.to_datetime(time[old_enough])

# Load PACE granules

In [5]:
reload(grab_pace_granules)
granules, pace = grab_pace_granules.load_from_json('PACE_50clouds.json')

In [6]:
pace.head()

,id,polygon,time
0,PACE_OCI_L2_AOP_PACE_OCI.20240305T045359.L2.OC...,"POLYGON ((129.99634 19.95012, 105.26324 14.805...",2024-03-05 04:56:28.500000+00:00
1,PACE_OCI_L2_AOP_PACE_OCI.20240305T081040.L2.OC...,"POLYGON ((80.81132 19.9969, 56.07363 14.85543,...",2024-03-05 08:13:10+00:00
2,PACE_OCI_L2_AOP_PACE_OCI.20240305T112721.L2.OC...,"POLYGON ((31.63485 20.04028, 6.9071 14.89843, ...",2024-03-05 11:29:50.500000+00:00
3,PACE_OCI_L2_AOP_PACE_OCI.20240305T143902.L2.OC...,"POLYGON ((-14.32906 2.23116, -38.0179 -2.80614...",2024-03-05 14:41:31.500000+00:00
4,PACE_OCI_L2_AOP_PACE_OCI.20240305T162722.L2.OC...,"POLYGON ((-44.22893 37.98507, -73.20055 32.449...",2024-03-05 16:29:51.500000+00:00

In [16]:
key0 = list(granules.keys())[0]
granule0 = granules[key0]

## Polygon

In [11]:
spt = rs_ea.extract_spatial_extent(granule0)
dshap = rs_ea.create_shapely_geometries(spt)
dshap

{'polygons': [<POLYGON ((129.996 19.95, 105.263 14.806, 109.514 -2.955, 133.203 2.081, 129...>],
 'rectangles': [],
 'points': [],
 'lines': []}

In [12]:
key0

'PACE_OCI_L2_AOP_PACE_OCI.20240305T045359.L2.OC_AOP.V3_0.nc_3.0'

In [12]:
key0 = list(granules.keys())[0]
granule0 = granules[key0]
granule0

{'meta': {'concept-type': 'granule',
  'concept-id': 'G3401489227-OB_CLOUD',
  'revision-id': 1,
  'native-id': 'PACE_OCI_L2_AOP_PACE_OCI.20240305T045359.L2.OC_AOP.V3_0.nc_3.0',
  'collection-concept-id': 'C3385049983-OB_CLOUD',
  'provider-id': 'OB_CLOUD',
  'format': 'application/vnd.nasa.cmr.umm+json',
  'revision-date': '2025-02-10T18:14:16.685Z'},
 'umm': {'TemporalExtent': {'RangeDateTime': {'BeginningDateTime': '2024-03-05T04:53:59Z',
    'EndingDateTime': '2024-03-05T04:58:58Z'}},
  'GranuleUR': 'PACE_OCI_L2_AOP_PACE_OCI.20240305T045359.L2.OC_AOP.V3_0.nc_3.0',
  'SpatialExtent': {'HorizontalSpatialDomain': {'Geometry': {'GPolygons': [{'Boundary': {'Points': [{'Latitude': 19.95012,
          'Longitude': 129.99634},
         {'Latitude': 14.80566, 'Longitude': 105.26324},
         {'Latitude': -2.95512, 'Longitude': 109.51402},
         {'Latitude': 2.08065, 'Longitude': 133.20255},
         {'Latitude': 19.95012, 'Longitude': 129.99634}]}}]}}},
  'ProviderDates': [{'Date': '2025-02-10T18:01:18Z', 'Type': 'Insert'},
   {'Date': '2025-02-10T17:44:19.833Z', 'Type': 'Update'}],
  'CollectionReference': {'ShortName': 'PACE_OCI_L2_AOP', 'Version': '3.0'},
  'RelatedUrls': [{'URL': 'https://oceandata.sci.gsfc.nasa.gov/browse_images/PACE_OCI.20240305T045359.L2.OC_AOP.V3_0.nc.png',
    'Format': 'PNG',
    'MimeType': 'image/png',
    'Type': 'GET RELATED VISUALIZATION'},
   {'URL': 'https://obdaac-tea.earthdatacloud.nasa.gov/ob-cumulus-prod-public/PACE_OCI.20240305T045359.L2.OC_AOP.V3_0.nc',
    'Description': 'Download PACE_OCI.20240305T045359.L2.OC_AOP.V3_0.nc',
    'Type': 'GET DATA'},
   {'URL': 's3://ob-cumulus-prod-public/PACE_OCI.20240305T045359.L2.OC_AOP.V3_0.nc',
    'Description': 'This link provides direct download access via S3 to the granule',
    'Type': 'GET DATA VIA DIRECT ACCESS'},
   {'URL': 'https://obdaac-tea.earthdatacloud.nasa.gov/s3credentials',
    'Description': 'api endpoint to retrieve temporary credentials valid for same-region direct s3 access',
    'Type': 'VIEW RELATED INFORMATION'}],
  'CloudCover': 49.5,
  'DataGranule': {'Identifiers': [{'IdentifierType': 'ProducerGranuleId',
     'Identifier': 'PACE_OCI.20240305T045359.L2.OC_AOP.V3_0.nc'}],
   'DayNightFlag': 'Day',
   'ProductionDateTime': '2025-02-10T17:44:19.833Z',
   'ArchiveAndDistributionInformation': [{'SizeInBytes': 407917518,
     'Format': 'netCDF-4',
     'Name': 'PACE_OCI.20240305T045359.L2.OC_AOP.V3_0.nc',
     'MimeType': 'application/x-netcdf'}]},
  'Platforms': [{'Instruments': [{'ShortName': 'OCI'}], 'ShortName': 'PACE'}],
  'MetadataSpecification': {'URL': 'https://cdn.earthdata.nasa.gov/umm/granule/v1.6.6',
   'Name': 'UMM-G',
   'Version': '1.6.6'}}}

In [14]:
granule0['umm']['RelatedUrls'][1]

{'URL': 'https://obdaac-tea.earthdatacloud.nasa.gov/ob-cumulus-prod-public/PACE_OCI.20240305T045359.L2.OC_AOP.V3_0.nc',
 'Description': 'Download PACE_OCI.20240305T045359.L2.OC_AOP.V3_0.nc',
 'Type': 'GET DATA'}

In [22]:
tstart + tend

TypeError: unsupported operand type(s) for +: 'Timestamp' and 'Timestamp'

In [26]:
tstart + (tend - tstart)/2

Timestamp('2024-03-05 04:56:28.500000+0000', tz='UTC')

----

In [15]:
reload(rs_ea)
tbl = rs_ea.build_granule_table(granules)

In [16]:
tbl

,id,polygon,time,CC,url
0,PACE_OCI_L2_AOP_PACE_OCI.20240305T045359.L2.OC...,"POLYGON ((129.99634 19.95012, 105.26324 14.805...",2024-03-05 04:56:28.500000+00:00,49.5,https://obdaac-tea.earthdatacloud.nasa.gov/ob-...
1,PACE_OCI_L2_AOP_PACE_OCI.20240305T081040.L2.OC...,"POLYGON ((80.81132 19.9969, 56.07363 14.85543,...",2024-03-05 08:13:10+00:00,48.2,https://obdaac-tea.earthdatacloud.nasa.gov/ob-...
2,PACE_OCI_L2_AOP_PACE_OCI.20240305T112721.L2.OC...,"POLYGON ((31.63485 20.04028, 6.9071 14.89843, ...",2024-03-05 11:29:50.500000+00:00,42.7,https://obdaac-tea.earthdatacloud.nasa.gov/ob-...
3,PACE_OCI_L2_AOP_PACE_OCI.20240305T143902.L2.OC...,"POLYGON ((-14.32906 2.23116, -38.0179 -2.80614...",2024-03-05 14:41:31.500000+00:00,46.1,https://obdaac-tea.earthdatacloud.nasa.gov/ob-...
4,PACE_OCI_L2_AOP_PACE_OCI.20240305T162722.L2.OC...,"POLYGON ((-44.22893 37.98507, -73.20055 32.449...",2024-03-05 16:29:51.500000+00:00,48.9,https://obdaac-tea.earthdatacloud.nasa.gov/ob-...
...,...,...,...,...,...
4649,PACE_OCI_L2_AOP_PACE_OCI.20250501T163649.L2.OC...,"POLYGON ((-39.70046 -17.20359, -64.99458 -22.4...",2025-05-01 16:39:18.500000+00:00,34.9,https://obdaac-tea.earthdatacloud.nasa.gov/ob-...
4650,PACE_OCI_L2_AOP_PACE_OCI.20250501T165149.L2.OC...,"POLYGON ((-50.29488 41.55137, -80.64542 35.865...",2025-05-01 16:54:18.500000+00:00,47.6,https://obdaac-tea.earthdatacloud.nasa.gov/ob-...
4651,PACE_OCI_L2_AOP_PACE_OCI.20250501T195832.L2.OC...,"POLYGON ((-93.50951 0.57069, -117.21605 -4.479...",2025-05-01 20:01:01.500000+00:00,46.2,https://obdaac-tea.earthdatacloud.nasa.gov/ob-...
4652,PACE_OCI_L2_AOP_PACE_OCI.20250501T201332.L2.OC...,"POLYGON ((-99.51873 59.34401, -141.90399 52.34...",2025-05-01 20:16:01.500000+00:00,44.9,https://obdaac-tea.earthdatacloud.nasa.gov/ob-...
4653,PACE_OCI_L2_AOP_PACE_OCI.20250501T213653.L2.OC...,"POLYGON ((-118.10001 0.56717, -141.8006 -4.481...",2025-05-01 21:39:22.500000+00:00,46.7,https://obdaac-tea.earthdatacloud.nasa.gov/ob-...